# permissions for end users to edit notifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: notifications-operator
    app.kubernetes.io/managed-by: kustomize
  name: notification-editor-role
rules:
- apiGroups:
  - notifications-operator.notifications-operator.com
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifications-operator.notifications-operator.com
  resources:
  - notifications/status
  verbs:
  - get
